language: php

php:
    - 5.3
    - 5.4

env:
    - SYMFONY_VERSION=origin/2.0
    - SYMFONY_VERSION=origin/master

before_script:
    - curl -s http://getcomposer.org/installer | php
    - COMPOSER_ROOT_VERSION=dev-master php composer.phar --dev install

script:
    - phpunit
    - bin/atoum -d Tests/Units

notifications:
    email:
        recipients:
            - py.stephane1@gmail.com
        on_success: change
        on_failure: change
