language: php

php:
    - 7.2
    - 7.3
    - 8.0

install: composer install -n

script:
    - bin/atoum -ncc

notifications:
    email:
        recipients:
            - py.stephane1@gmail.com
        on_success: change
        on_failure: change
